### ISSUE TITLE
gl2ps backend

### ISSUE THREAD

**Issue by stuaxo** [moderngl/glcontext#11]
Having a GL2PS backend could open up interesting possibilities, for print, PDF and SVG output

http://geuz.org/gl2ps/

Gnu Octave and VTK are two existing bits of software that can use GL2PS.

**Comment by szabolcsdombi** [comment]
I am closing this because it is not doable for glcontext/moderngl.
Generating SVG-s with or without GL2PS is not simple and could never cover all the features ModernGL provide.

To have nice visualization in web documents / notebooks a WebGL2 backend would do best.
PDFs won't be supported.

PS: web support is already working, it is not stable yet

Thank you
