### ISSUE TITLE
Default glversion

### ISSUE THREAD

**Issue by einarf** [moderngl/glcontext#4]
I have a sneaking suspicion glcontext might have a different behavior when it comes to requesting an opengl verison. In moderngl 5 users normaly omitted this info. We pass 330 as default value. This version number is set in the context parameters.

Will there be any issues when a context version is created as 330 when the user wanted the highest context? Is there any difference between window and standalone in this area?

**Comment by cprogrammer1994** [comment]
> Will there be any issues when a context version is created as 330 when the user wanted the highest context?

it is not possible to check with moderngl if an opengl feature is supported by the current version so users must know what version do they require. in most cases 330 is just ok to render basic stuff.

I don't want to provide the system maximum because the same code will sometimes run and sometimes don't (ex: compute shaders would work without explicitly asking for a 430+ but not on a software mesa driver # as of 2019)

> Is there any difference between window and standalone in this area?

probably yes

general window implementations provide system maximum or user configured.
single purpose windows (built just for a given application) may provide minimum required.

standalone contexts are closer to the single purpose windows where the user should explicitly decide what version is the minimum required (default version 330 does not depend on the system or any windows around)

**Comment by einarf** [comment]
Yup. Makes total sense.

**Comment by einarf** [comment]
Looks good in win an darwin so far. Just a bit more testing and I'll close this one.

**Comment by einarf** [comment]
Everything looks good!

- The `version_code` will update to the actual context version created by the backend
- When creating standalone context on most platforms you will get the exact version requested
- If `require` is not passed in for standalone contexts you'll most likely get 330
- The backend properly reports `version_code` in detect mode.

All this makes sense and should be compatible with older versions.
