### ISSUE TITLE
x11: Crash when using share mode

### ISSUE THREAD

**Issue by einarf** [moderngl/glcontext#9]
Currently the x11 crashes in share mode.

Fixing this is not a blocker for releasing glcontext 2.0 or moderngl 5.6.

**Comment by ProfFan** [comment]
Encountered (maybe) this:

```
X Error of failed request:  BadMatch (invalid parameter attributes)
  Major opcode of failed request:  151 (GLX)
  Minor opcode of failed request:  5 (X_GLXMakeCurrent)
  Serial number of failed request:  291
  Current serial number in output stream:  291
```

**Comment by szabolcsdombi** [comment]
The sharing mode supposed to work the opposite way.
To properly use sharing the following is recommended:

1. Create a headless context with moderngl.
2. Create any number of windows.
3. For each window create an OpenGL context (if it was not created already)
4. Ask the system to make these context "shared" with the headless context.

This works out of the box with many window libraries, step 4 usually requires a ctypes call to `wglShareLists` or similar. Since the window is usually created "empty of resource" this method works even better than the previous one.
